#!/bin/sh

echo "--school"; node loadEbData.js --school --pingOnly dataFiles/eb/schoolSetup/school.eb;

echo "--gradeLevel"; node loadEbData.js --gradeLevel --pingOnly dataFiles/eb/schoolSetup/gradeLevel.eb;

echo "--gradeLevelSchool"; node loadEbData.js --gradeLevelSchool --pingOnly dataFiles/eb/schoolSetup/gradeLevelSchool.eb;

echo "--term"; node loadEbData.js --term --pingOnly -- dataFiles/eb/schoolSetup/term.eb;

echo "--termSchool"; node loadEbData.js --termSchool --pingOnly -- dataFiles/eb/schoolSetup/termSchool.eb;

echo "--schoolSetCurrentTerm"; node loadEbData.js --schoolSetCurrentTerm --pingOnly -- dataFiles/eb/schoolSetup/school.eb;

echo "--student"; node loadEbData.js --student --pingOnly -- dataFiles/eb/peopleSetup/student.eb;

echo "--teacher"; node loadEbData.js --teacher --pingOnly -- dataFiles/eb/peopleSetup/teacher.eb;

echo "--homeroom"; node loadEbData.js --homeroom --skipFirstLine --pingOnly -- dataFiles/eb/peopleSetup/homeroom.eb;

echo "--studentAssignment"; node loadEbData.js --studentAssignment --pingOnly dataFiles/eb/studentAssignment.eb;

echo "--teacherAssignment"; node loadEbData.js --teacherAssignment --pingOnly dataFiles/eb/teacherAssignment.eb;

